import Footer from "@/components/footer";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/sonner";
import { UserProvider } from "@/lib/user-role";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<UserProvider>
			<div className="flex flex-col min-h-screen">
				<Header />
				<main className="flex-1">{children}</main>
				<Toaster />
				<Footer />
			</div>
		</UserProvider>
	);
}
